<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
$meigee_minimalism_general = MAGE::helper('ThemeOptionsMinimalism')->getThemeOptionsMinimalism('meigee_minimalism_general');
$footer_status = $meigee_minimalism_general['footer']['footer_status'];
$footer_static = $meigee_minimalism_general['footer']['footer_static'];
?>
<footer id="footer"<?php if($footer_status == 0){echo ' class="original"';}?>>
	<?php if($footer_status == 1): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer_static)->toHtml() ?>
	<?php else: ?>
		<div id="footer_bottom">
			<div class="container_12">
				<div class="grid_12">
					<?php echo $this->getChildHtml('lang_curr') ?>
					<?php echo $this->getChildHtml('store_switcher') ?>
					<address><?php echo $this->getCopyright() ?></address>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	<?php endif; ?>
	<div class="clear"></div>
</footer>