<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $random = rand(5, 1500);
?>
<section class="grid_6 block-subscribe omega">
	<div class="indent">
		<h3><?php echo $this->__('Newsletter') ?></h3> 
		<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail_<?php echo $random; ?>">
			<div class="block-content">            
				<label for="newsletter_<?php echo $random; ?>"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
				<div class="input-box">
					<input type="text" name="email" id="newsletter_<?php echo $random; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" value="<?php echo $this->__('Sign up for our newsletter') ?>" onblur="if (this.value=='') this.value = '<?php echo $this->__('Sign up for our newsletter') ?>'" onfocus="if (this.value=='<?php echo $this->__('Sign up for our newsletter') ?>') this.value = ''" />
					<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
					<div class="clear"></div>
				</div>
			</div>
		</form>
		<script type="text/javascript">
		//<![CDATA[
			var footerNewsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail_<?php echo $random; ?>');
		//]]>
		</script>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</section>