<?php
$installer = $this;
$installer->startSetup();
$installer->addAttributeGroup('catalog_product', 'Default', 'Meigee - Minimalism options', 9000);
$installer->addAttribute('catalog_product', 'minimalism_prsku', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product SKU',
    'note' => 'Will be displayed under product title',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 1,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prlayout', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Page Layout',
    'note' => 'Choose layout for product page',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_productlayout',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 2,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prprevnext', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Prev and Next product buttons',
    'note' => 'Allows you to move between products within a category just in one click',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 3,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prscrollingimages', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Scrolling Images',
    'note' => 'Replaces more views block with image scrolling images',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 4,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prmoreviews', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'More views block',
    'note' => 'Slider option will work if product has more images than can be displayed in one line',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_slider',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 5,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prrelated', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Related products block',
    'note' => 'Slider option will work if product has more related products than can be displayed in one line',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_slider',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 6,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_relatedpos', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Related products position',
    'note' => 'Choose position of this block',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_relatedpos',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 6,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prcolleteral', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Collateral block',
    'note' => 'Choose how collateral prodcut will be displayed',
    'source'            => 'ThemeOptionsMinimalism/attribute_source_collateral',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 7,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'minimalism_prcustom', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => 'Under product description',
    'note' => 'Replaces all static blocks set in product page options',
    'backend'       => '',
    'sort_order' => 8,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'wysiwyg_enabled' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_product', 'minimalism_prtabs', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Products Tabs',
    'note'          => 'Comma separated list of static block identifiers. These static blocks will be displayed one below the other',
    'backend'       => '',
    'sort_order' => 9,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_product', 'minimalism_prrelatedcontent', array(
    'group'         => 'Meigee - Minimalism options',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => '"Related" static block',
    'note' => 'Replaces all static blocks set in product page options',
    'backend'       => '',
    'sort_order' => 10,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'wysiwyg_enabled' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->endSetup();