<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2015 MeigeeTeam. (http://www.meigeeteam.com)
 */

$blockSwitch = $this->getLayout()->getBlockSingleton('Mage_Page_Block_Switch');
$blockCurrency = $this->getLayout()->getBlockSingleton('Mage_Directory_Block_Currency');
?>
<?php if((count($blockSwitch->getStores())) > 1 || $blockCurrency->getCurrencyCount() > 1) : ?>
	<div class="language-currency-wrapper<?php if((count($blockSwitch->getStores())) > 1 && $blockCurrency->getCurrencyCount() > 1){echo ' with-border';} ?>">
		<div class="language-currency-block">
			<?php if((count($blockSwitch->getStores())) > 1) :?>
				<span class="language">
					<?php $currentLang = Mage::app()->getStore()->getName(); ?>
					<img src="<?php echo $this->getSkinUrl('images/lang/'.$this->escapeHtml($currentLang).'.png') ?>" <?php echo MAGE::helper('ThemeOptionsMinimalism/Retina')->getRetinaData('languages', $currentLang); ?> alt="<?php echo $currentLang; ?>" />
				</span>
			<?php endif; ?>
			<?php if($blockCurrency->getCurrencyCount() > 1): ?>
				<span class="currency">
					<?php echo '<span class="icon">' . Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . '</span>' . $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode() .'<i class="fa fa-caret-down"></i>'; ?>
				</span>
			<?php endif; ?>
		</div>
		<div class="language-currency-dropdown">
			<?php echo $this->getLayout()->createBlock('directory/currency')->setTemplate('directory/currency_header.phtml')->toHtml(); ?>
			<?php echo $this->getLayout()->createBlock('page/switch')->setTemplate('page/switch/languages.phtml')->toHtml(); ?>
		</div>
		<div class="clear"></div>
	</div>
<?php endif; ?>